name: Main

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name'
        required: true


permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npx -y @vscode/vsce package
      # - name: Generate release tag
      #   id: tag
      #   run: |
      #     echo "release_tag=MediaConverter_$(date +"%Y.%m.%d_%H%M")" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: "**/*.vsix"
