name: Main

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without publish package"
        type: boolean
        default: true
      tag:
        description: "Release tag name"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build-release
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files

  bundle:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - name: darwin-x64
            cpu: x64
            os: darwin
          - name: darwin-arm64
            cpu: arm64
            os: darwin
          - name: win32-x64
            cpu: x64
            os: win32
          - name: linux-x64
            cpu: x64
            os: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-files
      - name: Install platform dependencies
        run: npm i --production --cpu=${{ matrix.cpu }} --os=${{ matrix.os }}
      - name: Package VSIX
        run: npm run package-vsix --target=${{ matrix.name }}
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}

  release:
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download files
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ !github.event.inputs.dry_run }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: MediaConverter-v${{ jq -r .version < ./package.json }}
          files: "**/*.vsix"
