name: Main

on:
  - workflow_dispatch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install
        run: npm ci
      - name: Build
        run: npx -y vsce package
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::MediaConverter_$(date +"%Y.%m.%d_%H%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: "**/*.vsix"
